// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD39KIyLEgIUGqCvXN3j8PSbzScuz_8Jw',
    appId: '1:776812728950:web:99c8b5b6811f06e18cc557',
    messagingSenderId: '776812728950',
    projectId: 'shop-app-9f7e6',
    authDomain: 'shop-app-9f7e6.firebaseapp.com',
    databaseURL: 'https://shop-app-9f7e6-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-9f7e6.appspot.com',
    measurementId: 'G-9TLGRBD4GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZOD9y077TVGHtuMYx4NSaPc4vxQilDU',
    appId: '1:776812728950:android:733ddc7c6181fb0f8cc557',
    messagingSenderId: '776812728950',
    projectId: 'shop-app-9f7e6',
    databaseURL: 'https://shop-app-9f7e6-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-9f7e6.appspot.com',
  );
}
